/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package taxi.fleet.oop;

import taxi.fleet.oop.booking.BookingCenter;
import taxi.fleet.oop.communication.DirectCommunicationStrategy;
import taxi.fleet.oop.communication.LogCommunicationStrategy;
import taxi.fleet.oop.dashboard.BookingDashboard;
import taxi.fleet.oop.dashboard.Dashboard;
import taxi.fleet.oop.taxi.Taxi;
import taxi.fleet.oop.taxi.TaxiFleet;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws InterruptedException {

        TaxiFleet fleet = new TaxiFleet();
        BookingCenter bookingCenter = new BookingCenter();

        Taxi taxi1 = new Taxi("T1", "Location1", bookingCenter);
        taxi1.getMessageCommunicationAgent().setCommunicationStrategy(
            LogCommunicationStrategy.of(DirectCommunicationStrategy.get()));
        fleet.addTaxi(taxi1);

        Taxi taxi2 = new Taxi("T2", "Location2", bookingCenter);
        fleet.addTaxi(taxi2);

        Dashboard dashboard = new BookingDashboard(bookingCenter);
        dashboard.displayStatistics();
        fleet.listAllTaxis();

        bookingCenter.newBooking("B1", "John Doe");
        dashboard.displayStatistics();
        Taxi taxi3 = new Taxi("T3", "Location3", bookingCenter);
        fleet.addTaxi(taxi3);
        fleet.listAllTaxis();

        bookingCenter.newBooking("B2", "Elma Soft");
        dashboard.displayStatistics();
        fleet.listAllTaxis();
    }
}
